FROM mcr.microsoft.com/dotnet/sdk:5.0-buster-slim-arm64v8 AS build-env
WORKDIR /app

COPY *.csproj ./
RUN dotnet restore

COPY . ./
RUN dotnet publish -c Release -o out -r linux-arm64 -f net5.0

FROM mcr.microsoft.com/dotnet/runtime:5.0-buster-slim-arm64v8 as base
WORKDIR /app
COPY --from=build-env /app/out ./

RUN useradd -ms /bin/bash moduleuser
RUN usermod -a -G uucp moduleuser
USER moduleuser

ENTRYPOINT ["dotnet", "ArduinoModule.dll"]