FROM mcr.microsoft.com/dotnet/sdk:5.0-buster-slim-arm32v7 AS build-env
WORKDIR /app

COPY *.csproj ./
RUN dotnet restore

COPY . ./
RUN dotnet publish -c Release -o out -r linux-arm -f net5.0

FROM mcr.microsoft.com/dotnet/runtime:5.0-buster-slim-arm32v7 as base
WORKDIR /app
COPY --from=build-env /app/out ./

RUN useradd -ms /bin/bash moduleuser
USER moduleuser

ENTRYPOINT ["dotnet", "ArduinoModule.dll"]